name: fly_io_client
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.4

dependencies:
  collection: ^1.18.0
  http: ^1.1.0
  logging: ^1.2.0

dev_dependencies:
  dotenv: ^4.2.0
  lints: ^2.0.0
  test: ^1.21.0
